drop table if exists us_gtmsales.countries;

create table us_gtmsales.countries
(
  country_id int,
  country_name text,
  country_code text,
  country_code_iso_3a text,
  geo_code text
);

insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (null, 'NOT REPORTABLE', null, null,'NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (null, 'ANONYMOUS', null, null,'NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (null, 'DELETED', null, null,'NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (null, 'N/A', null, null,'NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (1, 'ANDORRA', 'AD','AND','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (2, 'UNITED ARAB EMIRATES', 'AE','ARE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (2, 'UNITED ARAB OF EMIRATES', 'AE','ARE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (3, 'AFGHANISTAN', 'AF','AFG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (4, 'ANTIGUA AND BARBUDA', 'AG','ATG','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (5, 'ANGUILLA', 'AI','AIA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (6, 'ALBANIA', 'AL','ALB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (7, 'ARMENIA', 'AM','ARM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (8, 'NETHERLANDS ANTILLES', 'AN','ANT','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (9, 'ANGOLA', 'AO','AGO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (10, 'ANTARCTICA', 'AQ','ATA','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (11, 'ARGENTINA', 'AR','ARG','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (12, 'AMERICAN SAMOA', 'AS','ASM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (13, 'AUSTRIA', 'AT','AUT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (14, 'AUSTRALIA', 'AU','AUS','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (15, 'ARUBA', 'AW','ABW','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (16, 'ALAND ISLANDS', 'AX','ALA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (17, 'AZERBAIJAN', 'AZ','AZE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (18, 'BOSNIA AND HERZEGOVINA', 'BA','BIH','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (19, 'BARBADOS', 'BB','BRB','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (20, 'BANGLADESH', 'BD','BGD','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (21, 'BELGIUM', 'BE','BEL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (22, 'BURKINA FASO', 'BF','BFA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (23, 'BULGARIA', 'BG','BGR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (24, 'BAHRAIN', 'BH','BHR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (25, 'BURUNDI', 'BI','BDI','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (26, 'BENIN', 'BJ','BEN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (27, 'SAINT BARTHELEMY', 'BL','BLM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (28, 'BERMUDA', 'BM','BMU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (29, 'BRUNEI DARUSSALAM', 'BN','BRN','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (30, 'BOLIVIA', 'BO','BOL','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (31, 'BONAIRE, SINT EUSTATIUS AND SABA', 'BQ','BES','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (31, 'SINT EUSTATIUS AND SABA BONAIRE', 'BQ','BES','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (32, 'BRAZIL', 'BR','BRA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (33, 'BAHAMAS', 'BS','BHS','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (34, 'BHUTAN', 'BT','BTN','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (35, 'BOUVET ISLAND', 'BV','BVT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (36, 'BOTSWANA', 'BW','BWA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (37, 'BELARUS', 'BY','BLR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (38, 'BELIZE', 'BZ','BLZ','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (39, 'CANADA', 'CA','CAN','NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (40, 'COCOS (KEELING) ISLANDS', 'CC','CCK','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (41, 'DEMOCRATIC REPUBLIC OF THE CONGO', 'CD','COD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (41, 'CONGO, DEMOCRATIC REPUBLIC', 'CD','COD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (42, 'CENTRAL AFRICAN REPUBLIC', 'CF','CAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (43, 'CONGO', 'CG','COG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (44, 'SWITZERLAND', 'CH','CHE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (45, 'COTE DIVOIRE', 'CI','CIV','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (45, 'COTE D''IVOIRE', 'CI','CIV','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (46, 'COOK ISLANDS', 'CK','COK','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (47, 'CHILE', 'CL','CHL','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (48, 'CAMEROON', 'CM','CMR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (49, 'CHINA', 'CN','CHN','CHNA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (50, 'COLOMBIA', 'CO','COL','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (51, 'COSTA RICA', 'CR','CRI','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (52, 'SERBIA AND MONTENEGRO', 'CS','SCG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (53, 'CUBA', 'CU','CUB','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (54, 'CAPE VERDE', 'CV','CPV','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (55, 'CURACAO', 'CW','CUW','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (55, 'CURAÇAO', 'CW','CUW','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (56, 'CHRISTMAS ISLAND', 'CX','CXR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (57, 'CYPRUS', 'CY','CYP','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (58, 'CZECH REPUBLIC', 'CZ','CZE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (59, 'GERMANY', 'DE','DEU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (59, 'DEUTSCHLAND', 'DE','DEU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (60, 'DJIBOUTI', 'DJ','DJI','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (61, 'DENMARK', 'DK','DNK','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (62, 'DOMINICA', 'DM','DMA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (63, 'DOMINICAN REPUBLIC', 'DO','DOM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (64, 'ALGERIA', 'DZ','DZA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (65, 'ECUADOR', 'EC','ECU','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (66, 'ESTONIA', 'EE','EST','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (67, 'EGYPT', 'EG','EGY','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (68, 'WESTERN SAHARA', 'EH','ESH','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (69, 'ERITREA', 'ER','ERI','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (70, 'SPAIN', 'ES','ESP','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (71, 'ETHIOPIA', 'ET','ETH','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (72, 'FINLAND', 'FI','FIN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (73, 'FIJI', 'FJ','FJI','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (74, 'FALKLAND ISLANDS (MALVINAS)', 'FK','FLK','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (75, 'MICRONESIA, FEDERATED STATES OF', 'FM','FSM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (75, 'MICRONESIA', 'FM','FSM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (75, 'FEDERATED STATES OF MICRONESIA', 'FM','FSM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (76, 'FAROE ISLANDS', 'FO','FRO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (77, 'FRANCE', 'FR','FRA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (78, 'GABON', 'GA','GAB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (79, 'GREAT BRITAIN', 'GB','GB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (80, 'GRENADA', 'GD','GRD','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (81, 'GEORGIA', 'GE','GEO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (82, 'FRENCH GUIANA', 'GF','GUF','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (83, 'GUERNSEY', 'GG','GGY','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (84, 'GHANA', 'GH','GHA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (85, 'GIBRALTAR', 'GI','GIB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (86, 'GREENLAND', 'GL','GRL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (87, 'GAMBIA', 'GM','GMB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (88, 'GUINEA', 'GN','GIN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (89, 'GUADELOUPE', 'GP','GLP','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (90, 'EQUATORIAL GUINEA', 'GQ','GNQ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (91, 'GREECE', 'GR','GRC','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (92, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS','SGS','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (93, 'GUATEMALA', 'GT','GTM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (94, 'GUAM', 'GU','GUM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (95, 'GUINEA-BISSAU', 'GW','GNB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (96, 'GUYANA', 'GY','GUY','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (97, 'HONG KONG', 'HK','HKG','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (97, 'HONG KONG (CHINA)', 'HK','HKG','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (98, 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM','HMD','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (99, 'HONDURAS', 'HN','HND','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (100, 'CROATIA', 'HR','HRV','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (101, 'HAITI', 'HT','HTI','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (102, 'HUNGARY', 'HU','HUN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (103, 'INDONESIA', 'ID','IDN','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (104, 'IRELAND', 'IE','IRL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (105, 'ISRAEL', 'IL','ISR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (106, 'ISLE OF MAN', 'IM','IMN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (107, 'INDIA', 'IN','IND','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (108, 'BRITISH INDIAN OCEAN TERRITORY', 'IO','IOT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (109, 'IRAQ', 'IQ','IRQ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (110, 'IRAN, ISLAMIC REPUBLIC OF', 'IR','IRN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (110, 'IRAN', 'IR','IRN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (110, 'IRAN (ISLAMIC REPUBLIC OF)', 'IR','IRN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (111, 'ICELAND', 'IS','ISL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (112, 'ITALY', 'IT','ITA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (113, 'JERSEY', 'JE','JEY','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (114, 'JAMAICA', 'JM','JAM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (115, 'JORDAN', 'JO','JOR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (116, 'JAPAN', 'JP','JPN','JAPN');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (117, 'KENYA', 'KE','KEN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (118, 'KYRGYZSTAN', 'KG','KGZ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (119, 'CAMBODIA', 'KH','KHM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (120, 'KIRIBATI', 'KI','KIR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (121, 'COMOROS', 'KM','COM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (122, 'SAINT KITTS AND NEVIS', 'KN','KNA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (123, 'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', 'KP','PRK','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'KOREA', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'KOREA, REPUBLIC OF', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'KOREA,REPUBLIC OF', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'KOREA, REPUBLIC OF (SOUTH KOREA)', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'KOREA, SOUTH', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'SOUTH KOREA', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (124, 'REPUBLIC OF KOREA', 'KR','KOR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (125, 'KUWAIT', 'KU','KWT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (125, 'KUWAIT', 'KW','KWT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (126, 'CAYMAN ISLANDS', 'KY','CYM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (127, 'KAZAKHSTAN', 'KZ','KAZ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (128, 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'LA','LAO','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (128, 'LAOS', 'LA','LAO','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (129, 'LEBANON', 'LB','LBN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (130, 'SAINT LUCIA', 'LC','LCA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (131, 'LIECHTENSTEIN', 'LI','LIE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (132, 'SRI LANKA', 'LK','LKA','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (133, 'LIBERIA', 'LR','LBR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (134, 'LESOTHO', 'LS','LSO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (135, 'LITHUANIA', 'LT','LTU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (136, 'LUXEMBOURG', 'LU','LUX','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (137, 'LATVIA', 'LV','LVA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (138, 'LIBYAN ARAB JAMAHIRIYA', 'LY','LBY','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (138, 'LIBYA', 'LY','LBY','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (139, 'MOROCCO', 'MA','MAR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (140, 'MONACO', 'MC','MCO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (141, 'MOLDOVA, REPUBLIC OF', 'MD','MDA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (141, 'REPUBLIC OF MOLDOVA', 'MD','MDA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (141, 'MOLDOVA', 'MD','MDA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (142, 'MONTENEGRO', 'ME','MNE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (143, 'SAINT MARTIN (FRENCH PART)', 'MF','MAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (143, 'SAINT MARTIN', 'MF','MAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (144, 'MADAGASCAR', 'MG','MDG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (145, 'MARSHALL ISLANDS', 'MH','MHL','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (146, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK','MKD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (146, 'MACEDONIA', 'MK','MKD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (146, 'THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA', 'MK','MKD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (147, 'MALI', 'ML','MLI','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (148, 'MYANMAR', 'MM','MMR','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (149, 'MONGOLIA', 'MN','MNG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (150, 'MACAO', 'MO','MAC','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (150, 'MACAU', 'MO','MAC','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (151, 'NORTHERN MARIANA ISLANDS', 'MP','MNP','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (152, 'MARTINIQUE', 'MQ','MTQ','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (153, 'MAURITANIA', 'MR','MRT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (154, 'MONTSERRAT', 'MS','MSR','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (155, 'MALTA', 'MT','MLT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (156, 'MAURITIUS', 'MU','MUS','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (157, 'MALDIVES', 'MV','MDV','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (158, 'MALAWI', 'MW','MWI','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (159, 'MEXICO', 'MX','MEX','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (160, 'MALAYSIA', 'MY','MYS','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (161, 'MOZAMBIQUE', 'MZ','MOZ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (162, 'NAMIBIA', 'NA','NAM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (163, 'NEW CALEDONIA', 'NC','NCL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (164, 'NIGER', 'NE','NER','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (165, 'NORFOLK ISLAND', 'NF','NFK','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (166, 'NIGERIA', 'NG','NGA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (167, 'NICARAGUA', 'NI','NIC','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (168, 'NETHERLANDS', 'NL','NLD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (168, 'NETHERLANDS, THE', 'NL','NLD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (168, 'NL', 'NL','NLD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (169, 'NORWAY', 'NO','NOR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (170, 'NEPAL', 'NP','NPL','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (171, 'NAURU', 'NR','NRU','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (172, 'NIUE', 'NU','NIU','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (173, 'NEW ZEALAND', 'NZ','NZL','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (174, 'OMAN', 'OM','OMN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (175, 'PANAMA', 'PA','PAN','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (176, 'PERU', 'PE','PER','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (177, 'FRENCH POLYNESIA', 'PF','PYF','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (178, 'PAPUA NEW GUINEA', 'PG','PNG','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (179, 'PHILIPPINES', 'PH','PHL','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (180, 'PAKISTAN', 'PK','PAK','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (181, 'POLAND', 'PL','POL','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (182, 'SAINT PIERRE AND MIQUELON', 'PM','SPM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (183, 'PITCAIRN', 'PN','PCN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (183, 'PITCAIRN ISLANDS', 'PN','PCN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (184, 'PUERTO RICO', 'PR','PRI','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (185, 'PALESTINIAN TERRITORY, OCCUPIED', 'PS','PSE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (185, 'PALESTINIAN TERRITORY', 'PS','PSE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (185, 'PALESTINE', 'PS','PSE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (185, 'GAZA', 'PS','PSE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (186, 'PORTUGAL', 'PT','PRT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (187, 'PALAU', 'PW','PLW','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (188, 'PARAGUAY', 'PY','PRY','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (189, 'QATAR', 'QA','QAT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (190, 'REUNION', 'RE','REU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (191, 'ROMANIA', 'RO','ROU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (192, 'SERBIA', 'RS','SRB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (193, 'RUSSIA', 'RU','RUS','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (193, 'RUSSIAN FEDERATION', 'RU','RUS','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (194, 'RWANDA', 'RW','RWA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (195, 'SAUDI ARABIA', 'SA','SAU','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (196, 'SOLOMON ISLANDS', 'SB','SLB','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (197, 'SEYCHELLES', 'SC','SYC','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (198, 'SUDAN', 'SD','SDN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (199, 'SWEDEN', 'SE','SWE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (200, 'SINGAPORE', 'SG','SGP','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (201, 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'SH','SHN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (201, 'SAINT HELENA', 'SH','SHN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (202, 'SLOVENIA', 'SI','SVN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (203, 'SVALBARD AND JAN MAYEN', 'SJ','SJM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (204, 'SLOVAKIA', 'SK','SVK','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (205, 'SIERRA LEONE', 'SL','SLE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (206, 'SAN MARINO', 'SM','SMR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (207, 'SENEGAL', 'SN','SEN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (208, 'SOMALIA', 'SO','SOM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (209, 'SURINAME', 'SR','SUR','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (210, 'SOUTH SUDAN', 'SS','SSD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (211, 'SAO TOME AND PRINCIPE', 'ST','STP','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (212, 'EL SALVADOR', 'SV','SLV','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (213, 'SINT MAARTEN (DUTCH PART)', 'SX','SXM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (213, 'SINT MAARTEN', 'SX','SXM','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (214, 'SYRIAN ARAB REPUBLIC', 'SY','SYR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (215, 'SWAZILAND', 'SZ','SWZ','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (216, 'TURKS AND CAICOS ISLANDS', 'TC','TCA','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (217, 'CHAD', 'TD','TCD','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (218, 'FRENCH SOUTHERN TERRITORIES', 'TF','ATF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (218, 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'TF','ATF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (219, 'TOGO', 'TG','TGO','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (220, 'THAILAND', 'TH','THA','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (221, 'TAJIKISTAN', 'TJ','TJK','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (222, 'TOKELAU', 'TK','TKL','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (223, 'TIMOR-LESTE', 'TL','TLS','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (224, 'TURKMENISTAN', 'TM','TKM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (225, 'TUNISIA', 'TN','TUN','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (226, 'TONGA', 'TO','TON','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (227, 'TURKEY', 'TR','TUR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (228, 'TRINIDAD AND TOBAGO', 'TT','TTO','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (229, 'TUVALU', 'TV','TUV','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (230, 'TAIWAN', 'TW','TWN','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (230, 'TAIWAN (REPUBLIC OF CHINA)', 'TW','TWN','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (231, 'TANZANIA', 'TZ','TZA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (232, 'UKRAINE', 'UA','UKR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (233, 'UGANDA', 'UG','UGA','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (234, 'UNITED KINGDOM', 'UK','GBR','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (235, 'UNITED STATES MINOR OUTLYING ISLANDS', 'UM','UMI','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (236, 'UNITED STATES', 'US','USA','NAMER');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (237, 'URUGUAY', 'UY','URY','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (238, 'UZBEKISTAN', 'UZ','UZB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (239, 'HOLY SEE (VATICAN CITY STATE)', 'VA','VAT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (240, 'SAINT VINCENT AND THE GRENADINES', 'VC','VCT','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (241, 'VENEZUELA', 'VE','VEN','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (242, 'VIRGIN ISLANDS, BRITISH', 'VG','VGB','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (242, 'BRITISH VIRGIN ISLANDS', 'VG','VGB','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (243, 'VIRGIN ISLANDS, U.S.', 'VI','VIR','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (243, 'U.S. VIRGIN ISLANDS', 'VI','VIR','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (243, 'VIRGIN ISLANDS (U.S.)', 'VI','VIR','LATAM');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (244, 'VIETNAM', 'VN','VNM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (245, 'VANUATU', 'VU','VUT','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (246, 'WALLIS AND FUTUNA', 'WF','WLF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (247, 'SAMOA', 'WS','WSM','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (248, 'YEMEN', 'YE','YEM','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (249, 'MAYOTTE', 'YT','MYT','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (250, 'SOUTH AFRICA', 'ZA','ZAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (250, 'SOUTH AFRICA, REPUBLIC OF', 'ZA','ZAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (250, 'REPUBLIC OF SOUTH AFRICA', 'ZA','ZAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (250, 'SOUTH AFRICA, REPUBLIC OF', 'ZA','ZAF','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (251, 'ZAMBIA', 'ZM','ZMB','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (252, 'ZIMBABWE', 'ZW','ZWE','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (253, 'YUGOSLAVIA', 'YU','YUG','EMEA');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (254, 'EAST TIMOR', 'TP','TMP','APAC');
insert into us_gtmsales.countries (country_id, country_name, country_code, country_code_iso_3a, geo_code) values (255, 'KOSOVO', 'XK','RKS','EMEA');